apiVersion: v1
kind: Service
metadata:
  name: app2-svc
  namespace: victor
spec:
  selector:
    app: app2
    version: v2
  type: ClusterIP
  ports:
  - name: app2-port
    port: 8080 
    targetPort: 8080  