apiVersion: v1
kind: Service
metadata:
  name: app1-svc
  namespace: victor
spec:
  selector:
    app: app1
    version: v1
  type: ClusterIP
  ports:
  - name: app-port
    port: 8080 
    targetPort: 8080  
    